@startuml
left to right direction
actor User as "User"

rectangle "World Population" {
    usecase UC1 as "Display ALl countries information in the
    world sorted by largest population to smallest."

    usecase UC2 as "Display ALl countries information in a
                    continent sorted by largest population to smallest."

    usecase UC3 as "Display ALl countries information in a
                    region sorted by largest population to smallest."

    usecase UC4 as "Display top N countries information in the
                    world organized by population."

    usecase UC5 as "Display top N countries information in a
                    continent organized by population."

    usecase UC6 as "Display top N countries information in a
                    region organized by population."

    usecase UC7 as "Display all cities information in the
                     world organized by largest population to smallest."

    usecase UC8 as "Display all cities information in a
                    continent organized by largest population to smallest."

    usecase UC9 as "Display all cities information in a
                        region organized by largest population to smallest."

    usecase UC10 as "Display all cities information in a
                        country organized by largest population to smallest."

    usecase UC11 as "Display all cities information in a
                            district organized by largest population to smallest."

    usecase UC12 as "Display The top N populated cities
    in the world where N is provided by the user."

    usecase UC13 as "Display The top N populated cities
        in the continent where N is provided by the user."

    usecase UC14 as "Display The top N populated cities
        in the region where N is provided by the user."

    usecase UC15 as "Display The top N populated cities
        in the country where N is provided by the user."

    usecase UC16 as "Display The top N populated cities
        in the district where N is provided by the user."

    usecase UC17 as "Display All the capital cities in
        the world organised by largest population to smallest."

    usecase UC18 as "Display All the capital cities in
        the continent organised by largest population to smallest."

    usecase UC19 as "Display All the capital cities in
        the region organised by largest population to smallest."

    usecase UC20 as "Display The top N populated capital cities
        in the world where N is provided by the user."

    usecase UC21 as "Display The top N populated capital cities
        in the continent where N is provided by the user."

    usecase UC22 as "Display The top N populated capital cities
        in the region where N is provided by the user."

    usecase UC23 as "Display The population of people, people
        living in cities, and people not living in cities in each continent."

    usecase UC24 as "Display The population of people, people
        living in cities, and people not living in cities in each region."

    usecase UC25 as "Display The population of people, people
        living in cities, and people not living in cities in each country."

    User ---> UC1
    User ---> UC2
    User ---> UC3
    User ---> UC4
    User ---> UC5
    User ---> UC6
    User ---> UC7
    User ---> UC8
    User ---> UC9
    User ---> UC10
    User ---> UC11
    User ---> UC12
    User ---> UC13
    User ---> UC14
    User ---> UC15
    User ---> UC16

}

@enduml

